name: "Versioning Action"
description: "An action to update version on pull request merge"

inputs:
  gh-token:
    description: "The GitHub token for authentication."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
