name: "CI/CD on push to master"

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/versioning
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
